### ISSUE TITLE
Ensuring the OSMM is handled via the Project Lifecycle

### ISSUE THREAD

**Issue by vmbrasseur** [finos-labs/osmm#2]
Despite not being a software or standards project, we should probably do our best to follow the [Project Lifecycle](https://github.com/finos/community/blob/master/governance/Software-Projects/Project-Lifecycle.md) when contributing to and managing it.

How do we start that process?

**Comment by vmbrasseur** [comment]
Hi, @copiesofcopies! Could you please let us know why you closed the issue? We'd like to make sure the OSMM follows the correct procedure to become an official FINOS project.

**Comment by copiesofcopies** [comment]
Apologies, I misunderstood your question. @maoo what's the process here?

**Comment by maoo** [comment]
Hi @vmbrasseur and @copiesofcopies , I can definitely help with this!

The first step is to create an issue on github and follow our [project contribution template](https://github.com/finos/community/issues/new?assignees=agitana%2C+maoo%2C+TheJuanAndOnly99&labels=contribution&template=Software-Project-Contribution.md&title=Software+Project+Contribution+and+Onboarding). You can also find many examples on https://github.com/finos/community/issues?q=label%3Acontribution+

As part of the template, it will be requested to identify the Lead Maintainer (normally the person who creates the issue), other maintainers (who can merge PRs) and contributors (who is expected to send PRs).

Finally, it's worth mentioning that we use EasyCLA on all our hosted repositories, so every contributor must be onboarded on https://easycla.lfx.linuxfoundation.org . To onboard, you can simply raise a PR on https://github.com/finos/open-developer-platform/blob/master/EASYCLA_CHANGEME.md and follow instructions posted on the PR.

Feel free to ping me here or on Slack if you have further questions. TY!

**Comment by mindthegab** [comment]
I would agree that a proper contribution process is warranted, if we are maintaining this as a separate (software) project (it wasn't clear to me originally) vs being part of [the SIG](https://github.com/finos/open-source-readiness).

@maoo license wise the check should be pretty easy. At our most recent meeting, the Governing Board allowed CC-BY-SA and CC-BY as allowed licenses for our projects.

**Comment by mindthegab** [comment]
@vmbrasseur - can we get OSMM properly contributed as an incubating software project so it'll flow on the landscape.finos.org and there's a clear set of maintainers around it? 

The process is documented here - https://github.com/finos/community/blob/master/governance/Software-Projects/Contribution.md - it only takes opening an issue and then the FINOS team will process.

Thanks! 

/cc @agitana @mcleo-d

**Comment by mindthegab** [comment]
@vmbrasseur Per our convo yesterday, I've assigned the issue to you. 

Next step we discussed is for you (or anyone at Wipro as contributing entity) can start a [Contribution issue](https://github.com/finos/community/issues/new?assignees=agitana%2C+maoo%2C+TheJuanAndOnly99&labels=contribution&template=Software-Project-Contribution.md&title=Software+Project+Contribution+and+Onboarding). As discussed, for initial maintainers you can put @maoo Padmalav (and I discussed today with @copiesofcopies he could be in that list as well if you want). Once it's open I expect onboarding, if socialization and approval are successful, to be fairly quick since we have the infra already here.

Another option is to move the project to https://github.com/finos-labs/, which would be a much less formal process, with main difference that we accept DCO there - and when the model is more mature we can go through the formal contribution process. If you prefer this option, @maoo @mcleo-d can probably make this happen quite quickly

Let us know!

**Comment by mindthegab** [comment]
Hey @vmbrasseur - are you planning to do anything here, per our conversation? Otherwise I think we'll just move it to labs and FINOS can be the only maintainer.

**Comment by vmbrasseur** [comment]
Hey there, @mindthegab.

> The process is documented here - https://github.com/finos/community/blob/master/governance/Software-Projects/Contribution.md - it only takes opening an issue and then the FINOS team will process.

^^ that link 404s for me. Do you have an updated one?

**Comment by mindthegab** [comment]
Hi @vmbrasseur, yes since I posted the link 2 months ago, that page got moved to a subfolder (docs) to support the rollout of the community.finos.org microsite - the new URL for reference is https://github.com/finos/community/blob/master/docs/governance/Software-Projects/Contribution.md. 

That said, given the current state of the project, I think it makes most sense to move it to FINOS Labs (https://github.com/finos-labs/) which does not require a contribution process and will make for a much speedier development (DCO based) for the time being.

@maoo I'm assigning this issue to you so we can make the move and properly update docs to reference DCO - please put @copiesofcopies @maoo and Padmalav (@vmbrasseur can you provide his github ID?) as maintainers on that project.

**Comment by maoo** [comment]
@mindthegab @vmbrasseur - I've moved the repo to https://github.com/finos-labs/osmm , reviewed that Wipro team still has maintainer access and updated `CONTRIBUTING.md` to remove references to FINOS CLA.

I'll close this issue , but please reopen if you see anything missing. Thanks!
